test msg

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,26 +1,31 @@
 # Unique name for this workflow
-name: Salesforce DX CI Prerelease PR (scratch org)
+name: CI
 
 # Definition when the workflow should run
 on:
-    pull_request:
-        types: [opened, edited, synchronize, reopened]
+    workflow_dispatch:
+    push:
         branches:
-            - prerelease/spring[2-9][0-9]
-            - prerelease/summer[2-9][0-9]
-            - prerelease/winter[2-9][0-9]
+            - main
+        paths-ignore:
+            - 'sfdx-project.json'
+            - 'README.md'
 
 # Jobs to be executed
 jobs:
-    formatting-and-linting:
+    format-lint-lwc-tests:
         runs-on: ubuntu-latest
         steps:
-            # Checkout the code in the pull request
+            # Checkout the source code
             - name: 'Checkout source code'
               uses: actions/checkout@v2
 
+            # Install Volta to enforce proper node and package manager versions
+            - name: 'Install Volta'
+              uses: volta-cli/action@v1
+
             # Cache node_modules to speed up the process
-            - name: Restore node_modules cache
+            - name: 'Restore node_modules cache'
               id: cache-npm
               uses: actions/cache@v1
               with:
@@ -39,13 +44,9 @@ jobs:
             - name: 'Code formatting verification with Prettier'
               run: npm run prettier:verify
 
-            # Lint LWC
-            - name: 'Lint Lightning Web Components'
-              run: npm run lint:lwc
-
-            # Lint Aura
-            - name: 'Lint Aura components'
-              run: 'npm run lint:aura'
+            # Lint LWC / Aura
+            - name: 'Lint Lightning Web Components / Aura Components'
+              run: npm run lint
 
             # LWC unit tests
             - name: 'Unit test Lightning Web Components'
@@ -53,96 +54,104 @@ jobs:
 
             # Upload code coverage data
             - name: 'Upload code coverage for LWC to Codecov.io'
-              uses: codecov/codecov-action@v1
+              uses: codecov/codecov-action@v2.0.2
               with:
                   flags: LWC
 
     scratch-org-test:
         runs-on: ubuntu-latest
-        needs: formatting-and-linting
+        needs: format-lint-lwc-tests
+        if: ${{ github.actor != 'dependabot[bot]' }}
         steps:
             # Install Salesforce CLI
-            - name: Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
               run: |
-                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
-                  mkdir sfdx-cli
-                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
-                  ./sfdx-cli/install
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
 
-            # Checkout the code in the pull request
+            # Checkout the source code
             - name: 'Checkout source code'
               uses: actions/checkout@v2
 
-            # Install salesforcedx pre-release plugin
-            - name: 'Install salesforcedx pre-release plugin'
-              run: 'sfdx plugins:install salesforcedx@pre-release'
-
             # Store secret for dev hub
-            - name: 'Populate auth file with DEVHUB_PREREL_SFDX_URL secret'
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
               shell: bash
-              run: 'echo ${{ secrets.DEVHUB_PREREL_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
 
             # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
-              run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
+              run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Create scratch org
             - name: 'Create scratch org'
-              run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'
+              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
 
             # Deploy source to scratch org
             - name: 'Push source to scratch org'
-              run: 'sfdx force:source:push'
+              run: sfdx force:source:push
 
             # Assign permissionset
             - name: 'Assign permissionset to default user'
-              run: 'sfdx force:user:permset:assign -n dreamhouse'
+              run: sfdx force:user:permset:assign -n dreamhouse
 
             # Import sample data
             - name: 'Import sample data'
-              run: 'sfdx force:data:tree:import -p ./data/sample-data-plan.json'
+              run: sfdx force:data:tree:import -p ./data/sample-data-plan.json
 
             # Run Apex tests in scratch org
             - name: 'Run Apex tests'
-              run: 'sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20'
+              run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
+
+            # Delete temporary test file that Codecov is unable to parse
+            - name: 'Delete coverage file (temporary step)'
+              run: rm ./tests/apex/test-result-707*-codecoverage.json
 
             # Upload code coverage data
             - name: 'Upload code coverage for Apex to Codecov.io'
-              uses: codecov/codecov-action@v1
+              uses: codecov/codecov-action@v2.0.2
               with:
                   flags: Apex
 
             # Housekeeping
             - name: 'Delete scratch org'
               if: always()
-              run: 'sfdx force:org:delete -p -u scratch-org'
+              run: sfdx force:org:delete -p -u scratch-org
 
     trigger-packaging:
         runs-on: ubuntu-latest
         needs: scratch-org-test
         steps:
-            # Checkout the source code with history
+            # Checkout the source code
             - name: 'Checkout source code'
               uses: actions/checkout@v2
 
             # Check for package changes using git diff
-            - name: Check for package changes
+            - name: 'Check for package changes'
               id: checkForChanges
               run: |
-                  git fetch origin $GITHUB_BASE_REF --depth=1
-                  changedPaths=$( git diff-tree --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
+                  git fetch origin ${{ github.event.before }} --depth=1
+                  changedPaths=$( git diff-tree --name-only ${{ github.event.before }} $GITHUB_SHA )
                   set +e
                   hasChanges='false'
-                  if [[ $(echo "$changedPaths" | grep -c '^force-app$') == 1 ]]; then
+                  if [ $(echo "$changedPaths" | grep -c '^force-app') == 1 ]; then
                       hasChanges='true'
                   fi
                   echo "::set-output name=hasChanges::$hasChanges"
 
-            # Trigger Packaging Prerelease PR workflow
-            - name: 'Trigger Packaging Prerelease PR workflow if needed'
+            # Trigger packaging workflow if needed
+            - name: 'Trigger packaging workflow if needed'
               uses: peter-evans/repository-dispatch@v1.1.0
               if: ${{ steps.checkForChanges.outputs.hasChanges == 'true' }}
               with:
                   token: ${{ secrets.BOT_ACCESS_TOKEN }}
-                  event-type: package-prerelease-pr-event
+                  event-type: start-packaging
                   client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
